export const initial_frames = [
    {
        id: 1,
        name: "Рамка 1",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 2,
        name: "Рамка 2",
        width: 210,
        height: 297,
        baguetteId: 2,
        baguette: "РАH-23455",
        has_glass: true,
        has_backdrop: false,
        has_suspension: true
    },
    {
        id: 3,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 4,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 5,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 6,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 7,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 8,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 9,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 10,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 11,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 12,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 13,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 14,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 15,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 16,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 17,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 18,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 19,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 20,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 21,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    },
    {
        id: 22,
        name: "Рамка 3",
        width: 210,
        height: 297,
        baguetteId: 1,
        baguette: "РА-2345",
        has_glass: true,
        has_backdrop: false,
        has_suspension: false
    }
];
